[package]
name = "lnpbp_bech32"
version = "0.5.0-alpha.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "3.7.1"
bitcoin_hashes = "0.10.0"
strict_encoding = "1.6.0"
bech32 = "0.8.1"
deflate = { version = "0.8.6", optional = true }
inflate = { version = "0.4.5", optional = true }
serde_crate = { package = "serde", version = "1.0.0", features = ["derive"], optional = true }
serde_with = { version = "1.5.0", features = ["hex"], optional = true }
# serde_with_macros = { version = "1.2.0", optional = true } # Fix for the problem in 1.3.0

[features]
default = []
all = ["zip", "serde"]
zip = ["inflate", "deflate"]
serde = ["serde_crate", "serde_with", "bitcoin_hashes/serde", "amplify/serde"]
