[package]
name = "lnpbp_chain"
version = "0.5.0-alpha.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_crate = { package = "serde", version = "1.0.0", features = ["derive"], optional = true }
serde_with = { version = "1.5.0", features = ["hex"], optional = true }

[features]
serde = ["serde_crate", "serde_with"]
